# Generated by: Neurodocker version 0.7.0+0.gdc97516.dirty
# Timestamp: 2021/08/22 01:26:11 UTC
# 
# Thank you for using Neurodocker. If you discover any issues
# or ways to improve this software, please submit an issue or
# pull request on our GitHub repository:
# 
#     https://github.com/ReproNim/neurodocker

FROM ubuntu:bionic

USER root

ARG DEBIAN_FRONTEND="noninteractive"

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker

ENTRYPOINT ["/neurodocker/startup.sh"]

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           libopengl0 \
           build-essential \
           meshlab \
           blender=2.79.b+dfsg0-1ubuntu1.18.04.1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV SKLEARN_NO_OPENMP="1"

COPY [".", "/headcase-pipeline"]

ENV CONDA_DIR="/opt/miniconda-latest" \
    PATH="/opt/miniconda-latest/bin:$PATH"
RUN export PATH="/opt/miniconda-latest/bin:$PATH" \
    && echo "Downloading Miniconda installer ..." \
    && conda_installer="/tmp/miniconda.sh" \
    && curl -fsSL --retry 5 -o "$conda_installer" https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash "$conda_installer" -b -p /opt/miniconda-latest \
    && rm -f "$conda_installer" \
    && conda update -yq -nbase conda \
    && conda config --system --prepend channels conda-forge \
    && conda config --system --set auto_update_conda false \
    && conda config --system --set show_channel_urls true \
    && sync && conda clean -y --all && sync \
    && conda install -y -q --name base \
           "python=3" \
           "numpy" \
           "scipy" \
           "cython" \
    && sync && conda clean -y --all && sync \
    && bash -c "source activate base \
    &&   pip install --no-cache-dir  \
             "-r" \
             "/headcase-pipeline/requirements.txt"" \
    && pip install --upgrade numpy \
    && rm -rf ~/.cache/pip/* \
    && sync \
    && sed -i '$isource activate base' $ND_ENTRYPOINT

RUN useradd -m -s /bin/bash -G users headcase

ENV HOME="/home/headcase"

RUN mkdir /home/headcase/.config

RUN python -c 'import cortex'

WORKDIR /headcase-pipeline

ENTRYPOINT ["python", "/headcase-pipeline/make_headcase.py"]

RUN echo '{ \
    \n  "pkg_manager": "apt", \
    \n  "instructions": [ \
    \n    [ \
    \n      "base", \
    \n      "ubuntu:bionic" \
    \n    ], \
    \n    [ \
    \n      "install", \
    \n      [ \
    \n        "libopengl0", \
    \n        "build-essential", \
    \n        "meshlab", \
    \n        "blender=2.79.b+dfsg0-1ubuntu1.18.04.1" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "env", \
    \n      { \
    \n        "SKLEARN_NO_OPENMP": "1" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "copy", \
    \n      [ \
    \n        ".", \
    \n        "/headcase-pipeline" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "miniconda", \
    \n      { \
    \n        "use_env": "base", \
    \n        "activate": true, \
    \n        "conda_install": [ \
    \n          "python=3", \
    \n          "numpy", \
    \n          "scipy", \
    \n          "cython" \
    \n        ], \
    \n        "pip_install": [ \
    \n          "-r", \
    \n          "/headcase-pipeline/requirements.txt" \
    \n        ] \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "useradd -m -s /bin/bash -G users headcase" \
    \n    ], \
    \n    [ \
    \n      "env", \
    \n      { \
    \n        "HOME": "/home/headcase" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "mkdir /home/headcase/.config" \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "python -c '"'"'import cortex'"'"'" \
    \n    ], \
    \n    [ \
    \n      "workdir", \
    \n      "/headcase-pipeline" \
    \n    ], \
    \n    [ \
    \n      "entrypoint", \
    \n      "python /headcase-pipeline/make_headcase.py" \
    \n    ] \
    \n  ] \
    \n}' > /neurodocker/neurodocker_specs.json
